image:
  file: .gitpod/Dockerfile
tasks:
  - name: Set solana wallet
    command: echo $SOLANA_KEY | base64 -d  > /home/gitpod/.config/solana/id.json && solana airdrop 2 && exit
  - name: golang live
    env:
      PASETO_PRIVATE_KEY: abckey
      PASETO_EXPIRATION: 24h
      APP_PORT: 3000
      AUTH_EULA: "Signing means you agree to T&C listed here"
      GIN_MODE: debug
      DB_HOST: localhost
      DB_USERNAME: airex_gateway
      DB_PASSWORD: airex_gateway
      DB_NAME: airex_gateway
      DB_PORT: 5432
      ALLOWED_ORIGIN: "*"
      SIGNED_BY: MyriadFlow
      COLLECTION_PATH: generated_collections
    init: |
      go install gotest.tools/gotestsum@latest
      go get && go build -o build/solana-gateway
    command: |
      docker run --name="airex_gateway" --rm -d -p 5432:5432 \
      -e POSTGRES_PASSWORD=airex_gateway \
      -e POSTGRES_USER=airex_gateway \
      -e POSTGRES_DB=airex_gateway \
      postgres -c log_statement=all
      sleep 12
      gp sync-done db
      cp .env-sample .env
      mkdir generated_collections
      air
  
  - name: postgres shell
    command: |
      gp sync-await db
      docker exec -it airex_gateway psql -U airex_gateway
         
vscode:
  extensions:
    - golang.go